### ISSUE TITLE
能否修正module name和import name,以方便go mod使用

### ISSUE THREAD

**Issue by yangjuncode** [bilibili/discovery#15]
统一将 discovery 修改为 github.com/bilibili/discovery

目前需要手动clone,并且使用了 go mod的话,还要自己加 replace,比较麻烦

**Comment by lintanghui** [comment]
#16  已修改为github.com/bilibili

**Comment by yangjuncode** [comment]
> #16 已修改为github.com/bilibili

go.mod未修改,有编译问题
