### ISSUE TITLE
nodesproc 中只能获取到本zone的node

### ISSUE THREAD

**Issue by zhuanxuhit** [bilibili/discovery#20]
(d *Discovery) nodesproc 函数中，poll只会去获取本zone的节点信息，这样子更新后会覆盖本地其他zone的节点

**Comment by lintanghui** [comment]
恩  nodesproc的时候zone参数不应该传递,应该是获取所有zone节点信息

**Comment by zhuanxuhit** [comment]
现在开源的版本是bilibili内部目前使用的吗

**Comment by lintanghui** [comment]
> 现在开源的版本是bilibili内部目前使用的吗
是的，内部版本相比开源版本多了日志集成以及配置中心等内部定制的模块
