### ISSUE TITLE
关于docker 运行discovery 存在问题

### ISSUE THREAD

**Issue by HelloWorldZQ** [bilibili/discovery#22]
使用配置
[httpServer]
addr = "127.0.0.1:7171"
启动docker，服务只能被本地使用，非127.0.0.1 ip 访问被拒绝。
原因是 discovery 启动gin 的时候使用 httpServer.addr 监听. 将会拒绝所有非127.0.0.1  的请求，
容器也无法使用宿主ip 启动gin. 建议添加单独配置指定 gin 端口。
我本地添加新的配置项，测试通过
![image](https://user-images.githubusercontent.com/10047555/57972934-894b8900-79d3-11e9-9185-931daf14b2ea.png)

**Comment by felixhao** [comment]
把配置改成`0.0.0.0:7171`

**Comment by HelloWorldZQ** [comment]
![image](https://user-images.githubusercontent.com/10047555/58013793-f96c2300-7b29-11e9-8023-011dfb18eee0.png)
这个提示看着 。。。

**Comment by HelloWorldZQ** [comment]
@felixhao 不行的 还是会呗拒绝
这个地址会被 汇报上去。。
![image](https://user-images.githubusercontent.com/10047555/58014230-f58cd080-7b2a-11e9-839e-28d32ec1fc06.png)
logic 那边的code 都会调用0.0.0.0 这个ip 的discovery了
还是决定多加个端口配置比较合理
http server addr 是对外可见的 ip 和端口。
加个port 是启动服务使用的端口，如果有什么端口转发都可以实现

**Comment by lintanghui** [comment]
这个地方应该是在启动监听的时候自动转换为监听网卡地址，可以先修改配置使用网卡ip进行监听启动。我们在进行fix自动把ip转换为网卡ip

**Comment by HelloWorldZQ** [comment]
docker 启动的时候如果使用虚拟的网卡ip 的话，从宿主机外访问宿主ip：7171（或者容器的端口指向了宿主机其它ip） 就会被拒绝

**Comment by felixhao** [comment]
@HelloWorldZQ 需要先理清楚：

1. docker里启动discovery，配置文件将addr配置为`0.0.0.0:7171`
2. 启动依赖discovery的client，需要配置你对应docker的`ip:7171`

分清楚服务端和客户端的配置

**Comment by lintanghui** [comment]
@felixhao ， @HelloWorldZQ 的情况是他使用的discovery的服务自发现功能，地址配置为0.0.0.0的时候discovery 自己注册上去的服务地址会是0.0.0.0 client拿到后无法访问，如果直接使用容器的网卡ip进行注册，那么非宿主机也无法访问到discovery。如果使用docker应该需要你修改下docker的网络方式，或者在client里写死discovery的ip:port

**Comment by HelloWorldZQ** [comment]
@lintanghui  多谢 。就是 这种情况，我没有很好的表达我的意思，目前我只能添加了一个配置 解决这个
