### ISSUE TITLE
discover namesing 构造的请求有问题!

### ISSUE THREAD

**Issue by brewlin** [bilibili/discovery#23]
![image](https://user-images.githubusercontent.com/17773920/59099833-e2656780-8956-11e9-8397-7e53b8b30ecb.png)

构造的 请求 url 里面的参数怎么有重复的？
lastest_timestamp 有两个 因此报错

**Comment by brewlin** [comment]
定时拉去节点信息 的请求url  一直报错 发现调用discovery 的namesing
```
	dis := naming.New(conf.Conf.Discovery)
	resolver.Register(dis)
```

**Comment by lintanghui** [comment]
-404 是服务不存在，确保你的服务注册到discvory了
