### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by cssivision** [bilibili/discovery#24]
go build -v
Fetching https://github.com?go-get=1
Parsing meta tags from https://github.com?go-get=1 (status code 200)
can't load package: package github.com/bilibili/kratos: unknown import path "github.com/bilibili/kratos": cannot find module providing package github.com/bilibili/kratos

**Comment by lintanghui** [comment]
描述清楚详细信息
$ go version  
$ go env 
分别是啥
GO111MODULE  是否开启
