### ISSUE TITLE
节点有循环注册的现象，造成大量TCP连接

### ISSUE THREAD

**Issue by lgxnu** [bilibili/discovery#26]
如题
A节点收到注册请求，replicate给B节点和C节点，B节点又replicate给A,C节点，C节点又同步给了A,B如此，不断循环

**Comment by lintanghui** [comment]
discovery有判断注册的信息是否需要同步到其他节点。请贴出现象日志截图。
Register部分有判断是否需要replicate，请详细看代码复制部分，这里不可能出现重复注册。
先检查自身client是否不断在发register请求
