### ISSUE TITLE
Discovery Polls API 可用性问题

### ISSUE THREAD

**Issue by patricksuo** [bilibili/discovery#28]
Discovery 批量 polls 的时候，可以指定多个 app 。
如果其中一个监听的 app 完全下线，会导致整个 polls 一直返回 404 。

**Comment by sillyousu** [comment]
Discovery Client 核心设计意图是高可用。
如果因为一个 app 离线而不可用是违背 HA 目的的。

我认为 Disvoery Client 的高可用不应该假设『业务也是高可用的，不太可能一直完全离线』

**Comment by lintanghui** [comment]
#50
