### ISSUE TITLE
技术支持

### ISSUE THREAD

**Issue by mercyblitz** [Bilibili/discovery#3]
非常感谢 B 站同学在服务发现上耕耘，本人  [dubbo](https://github.com/apache/incubator-dubbo) 社区的小破开发，目前正在对服务发现这块做调研，请问目前该项目有没有更为直接技术支持的沟通渠道，除 github 之外，讨论更为细节方面的问题。

PS: 本人的微信 mercyblitz，欢迎交流和讨论！

**Comment by amorist** [comment]
github就可以讨论吧 拥抱开源

**Comment by mercyblitz** [comment]
666

**Comment by felixhao** [comment]
已加
