### ISSUE TITLE
README.md issue

### ISSUE THREAD

**Issue by xiak** [bilibili/discovery#41]
log_dir should change to log.dir in verion 1.1.0 in this string '-alsologtostderr is glog's flag，means print into stderr. If you hope print into file, can use -log_dir="/tmp"'

=====================================
[root@k8s-discovery1 discovery]# discovery
ERROR 08/09-02:48:39.217 /work/go/src/github.com/Bilibili/discovery/cmd/discovery/main.go:19 conf.Init() error(open discovery-example.toml: no such file or directory)
panic: open discovery-example.toml: no such file or directory

goroutine 1 [running]:
main.main()
        /work/go/src/github.com/Bilibili/discovery/cmd/discovery/main.go:20 +0x3c5
[root@k8s-discovery1 discovery]# discovery -h
Usage of discovery:
  -appid string
        appid is global unique application id, register by service tree. or use APP_ID env variable.
  -conf string
        config path (default "discovery-example.toml")
  -deploy.color string
        deploy.color is the identification of different experimental group.
  -deploy.env string
        deploy env. or use DEPLOY_ENV env variable, value: dev/fat1/uat/pre/prod etc. (default "dev")
  -discovery.nodes string
        discovery.nodes is seed nodes. value: 127.0.0.1:7171,127.0.0.2:7171 etc.
  -hostname string
        machine hostname (default "k8s-discovery1")
  -http string
        listen http dsn, or use HTTP env variable. (default "tcp://0.0.0.0:8000/?timeout=1s")
  -http.perf string
        listen http perf dsn, or use HTTP_PERF env variable. (default "tcp://0.0.0.0:2333")
  -log.agent string
        log agent dsn, or use LOG_AGENT env variable.
  -log.dir string
        log file `path, or use LOG_DIR env variable.
  -log.filter value
        log field for sensitive message, or use LOG_FILTER env variable, format: field1,field2.
  -log.module value
        log verbose for specified module, or use LOG_MODULE env variable, format: file=1,file2=2.
  -log.noagent
        force disable log agent print log to stderr,  or use LOG_NO_AGENT
  -log.stdout
        log enable stdout or not, or use LOG_STDOUT env variable.
  -log.v int
        log verbose level, or use LOG_V env variable.
  -prom_summary
        use summary in prometheus
  -region string
        avaliable region. or use REGION env variable, value: sh etc. (default "region01")
  -scheduler string
        scheduler info (default "scheduler.json")
  -trace string
        trace report dsn, or use TRACE env. (default "unixgram:///var/run/dapper-collect/dapper-collect.sock")
  -zone string
        avaliable zone. or use ZONE env variable, value: sh001/sh002 etc. (default "zone01")

**Comment by felixhao** [comment]
已修改~3Q
