### ISSUE TITLE
https://github.com/bilibili/kratos/issues/329#issue-492545751

### ISSUE THREAD

**Issue by dalaoting** [bilibili/discovery#47]
[一个服务在同一台机器无法向discovery注册多个](https://github.com/bilibili/kratos/issues/329#issue-492545751)

**Comment by lintanghui** [comment]
可以通过启动demo的时候export HOSTNAME=xxx 来设置不同的hostname，因为我们初始设计是按hostname来区分不同的instance的。目前可以通过手动设置HOSTNAME 这个环境变量来做隔离区分

**Comment by dalaoting** [comment]
那每次启动之前还要先执行一下export，略麻烦，不过这也是一种解决方案，谢谢
